#ppURL=https://tutorialsninja.com/demo/
#appURL=https://naveenautomationlabs.com/opencart/
#appURL=https://www.makemytrip.com
appURL=https://tutorialsninja.com/demo/
email=chaitanyapatil1777@gmail.com
password=Pass@123
searchProductName=fitbit
#execution_env=remote
execution_env=local

os=windows
#os=mac

browser=chrome
#browser=edge
#browser=firefox

